blog/entries/__init__.py
# coding=utf-8

blog/entries/blueprint.py
# coding=utf-8
import os

from flask import abort, Blueprint, flash, g, redirect, render_template, request, url_for
from flask_login import LoginManager, login_required
from werkzeug.utils import secure_filename

from blog.app import app, db
from blog.entries.form import EntryForm, ImageForm
from blog.helpers import g_object_list
from blog.models import Entry, Tag

entries = Blueprint('entries', __name__, template_folder='./templates')


def entry_list(template, query, **content):
    """
    Do the query and delegate the variable query to g_object_list().
    if body or title contain the word you typed in query box or URI,
    then you will see the result in the response page.
    """
    query = filter_status_by_user(query)

    valid_status = [Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT]
    query = query.filter(Entry.status.in_(valid_status))
    if request.args.get('q'):
        search = request.args.get('q')
        query = query.filter(
            (Entry.body.contains(search)) |
            (Entry.title.contains(search))
        )
    return g_object_list(template, query, **content)


def filter_status_by_user(query):
    if not g.user.is_authenticated:
        return query.filter(Entry.status == Entry.STATUS_PUBLIC)
    else:
        query = query.filter(
            (Entry.status == Entry.STATUS_PUBLIC) |
            ((Entry.author == g.user) &
             (Entry.status != Entry.STATUS_DELETED)))
    return query


def get_entry_or_404(slug, author=None):
    query = Entry.query.filter(Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()


@entries.route('/')
def index():
    get_entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', get_entries)


@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    if tags:
        return g_object_list('entries/tag_index.html', tags)
    abort(404)


@entries.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    if tag:
        entries = tag.entries.order_by(Entry.created_timestamp.desc())
        return entry_list('entries/tag_detail.html', entries, tag=tag)
    abort(404)


@entries.route('/<slug>')
def detail(slug):
    entry = Entry.query.filter(Entry.slug == slug).first()
    if entry:
        return render_template('entries/detail.html', entry=entry)
    abort(404)


@entries.route('/create/', methods=['POST', 'GET'])
@login_required
def create():
    form = EntryForm()
    if request.method == 'POST' and form.validate_on_submit():
        entry = form.save_entry(Entry(author=g.user))
        db.session.add(entry)
        db.session.commit()
        flash('Enrty {} has been created successfully'.format(entry.title), 'success')
        return redirect(url_for('.detail', slug=entry.slug))
    return render_template('entries/create.html', form=form)


@entries.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit(slug):
    form = EntryForm()
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST' and form.validate_on_submit():
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Enrty {} has been saved'.format(entry.title), 'success')
        return redirect(url_for('.detail', slug=entry.slug))
    return render_template('entries/edit.html', form=form, entry=entry)


@entries.route('/<slug>/delete', methods=['GET', 'POST'])
@login_required
def delete(slug):
    entry = get_entry_or_404(slug, author=None)
    if request.method == "POST":
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash('Enrty {} has been created deleted'.format(entry.title), 'success')
        return redirect(url_for('.index'))
    return render_template('entries/delete.html', entry=entry)


@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = ImageForm()
    if request.method == 'POST' and form.validate_on_submit():
        image_file = request.files['file']
        filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
        image_file.save(filename)
        flash('Saved {}'.format(os.path.basename(filename), 'success'))
        return redirect(url_for('entries.index'))
    return render_template('entries/image_upload.html', form=form)

entries/blueprint.py
# coding=utf-8
import os

from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from flask_login import LoginManager, login_required
from werkzeug.utils import secure_filename

from app import app, db
from entries.form import EntryForm, ImageForm
from helpers import g_object_list
from models import Entry, Tag

entries = Blueprint('entries', __name__, template_folder='./templates')


def entry_list(template, query, **content):
    """
    Do the query and delegate the variable query to g_object_list().
    if body or title contain the word you typed in query box or URI,
    then you will see the result in the response page.
    """
    query = filter_status_by_user(query)

    valid_status = [Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT]
    query = query.filter(Entry.status.in_(valid_status))
    if request.args.get('q'):
        search = request.args.get('q')
        query = query.filter(
            (Entry.body.contains(search)) |
            (Entry.title.contains(search))
        )
    return g_object_list(template, query, **content)


def filter_status_by_user(query):
    if not g.user.is_authenticated:
        return query.filter(Entry.status == Entry.STATUS_PUBLIC)
    else:
        query = query.filter(
            (Entry.status == Entry.STATUS_PUBLIC) |
            ((Entry.author == g.user) &
             (Entry.status != Entry.STATUS_DELETED)))
    return query


def get_entry_or_404(slug, author=None):
    query = Entry.query.filter(Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()


@entries.route('/')
def index():
    get_entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', get_entries)


@entries.route('/tags/')
def tag_index():
    tags = Tag.query.order_by(Tag.name)
    return g_object_list('entries/tag_index.html', tags)


@entries.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)


@entries.route('/<slug>')
def detail(slug):
    entry = Entry.query.filter(Entry.slug == slug).first()
    return render_template('entries/detail.html', entry=entry)


@entries.route('/create/', methods=['POST', 'GET'])
@login_required
def create():
    form = EntryForm()
    if request.method == 'POST' and form.validate_on_submit():
        entry = form.save_entry(Entry(author=g.user))
        db.session.add(entry)
        db.session.commit()
        flash('Enrty {} has been created successfully'.format(entry.title), 'success')
        return redirect(url_for('.detail', slug=entry.slug))
    return render_template('entries/create.html', form=form)


@entries.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit(slug):
    form = EntryForm()
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST' and form.validate_on_submit():
        entry = form.save_entry(entry)
        db.session.add(entry)
        db.session.commit()
        flash('Enrty {} has been saved'.format(entry.title), 'success')
        return redirect(url_for('.detail', slug=entry.slug))
    return render_template('entries/edit.html', form=form, entry=entry)


@entries.route('/<slug>/delete', methods=['GET', 'POST'])
@login_required
def delete(slug):
    entry = get_entry_or_404(slug, author=None)
    if request.method == "POST":
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash('Enrty {} has been created deleted'.format(entry.title), 'success')
        return redirect(url_for('.index'))
    return render_template('entries/delete.html', entry=entry)


@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = ImageForm()
    if request.method == 'POST' and form.validate_on_submit():
        image_file = request.files['file']
        filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
        image_file.save(filename)
        flash('Saved {}'.format(os.path.basename(filename), 'success'))
        return redirect(url_for('entries.index'))
    return render_template('entries/image_upload.html', form=form)

blog/entries/templates/entries/base_entries.html
{% extends 'base.html' %}

{% block sidebar %}
<form class="from-inline well" method="get" role="form">
    <div class="input-group">
        <input class="form-control input-xs" name="q" placeholder="Search..."
               value="{{ request.args.get('q', '') }}">
        <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go</button>
            </span>
    </div>
</form>
{% endblock %}

{% block content %}
    {% include "include/list.html" %}
    {% include "includes/page_links.html" %}
{% endblock %}

blog/entries/templates/entries/create.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    Create new entry
{% endblock %}

{% block content_title %}
    Create new entry
{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
        <div>
            {{ wtf.quick_form(form) }}
            {#            <div class="form-group">#}
            {#                <input type="text" class="form-control" placeholder="Search">#}
            <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
        </div>
{#        <div class="form-group">#}
{#            <div class="col-sm-offset-3 col-sm-9">#}
{#                <button type="submit" class="btn btn-default">Create</button>#}
{#                #}
{#            </div>#}
{#        </div>#}
    </form>
{% endblock %}

blog/entries/templates/entries/delete.html
{% extends 'base.html' %}

{% block title %}{{ entry.title }}{% endblock %}

{% block content_title %}{{ entry.title }}{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="post">
        <fieldset>
            <legend>
                Delete this Entry?
            </legend>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
        </fieldset>
    </form>
{% endblock %}

blog/entries/templates/entries/detail.html
{% extends 'base.html' %}

{% block title %}{{ entry.title }}{% endblock %}

{% block content_title %}{{ entry.title }}{% endblock %}

{% block sidebar %}
    <ul class="well nav nav-list">
        <li><h4>Tags</h4></li>
        {% for tag in entry.tags %}
            <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
    {% if g.user == entry.author %}
        <li><h4>Action</h4></li>
            <li><a href="{{ url_for('entries.edit', slug=entry.slug) }}">Edit</a></li>
            <li><a href="{{ url_for('entries.delete', slug=entry.slug) }}">Delete</a></li>
    {% endif %}
    </ul>
    <p>Published {{ entry.created_timestamp.strftime('%c') }}</p>
{% endblock %}

{% block content %}
    {{ entry.body }}
{% endblock %}

blog/entries/templates/entries/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Edit {{ entry.title }}{% endblock %}

{% block content_title %} Edit {{ entry.title }}{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
        {{ wtf.quick_form(form) }}
        <a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
    </form>
{% endblock %}

blog/entries/templates/entries/image_upload.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}

{% block title %}
    Upload an image
{% endblock %}


{% block content_title %}
    Upload an image
{% endblock %}

{% block content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

blog/entries/templates/entries/index.html
{% extends 'entries/base_entries.html' %}
{% block title %}
    Entries
{% endblock %}

{% block content_title %}
Entries
{% endblock %}

blog/entries/templates/entries/tag_detail.html
{% extends 'entries/base_entries.html' %}

{% block title %}{{ tag.name }} entries{% endblock %}

{% block content_title %}
    {{ tag.name }} entries
{% endblock %}

blog/entries/templates/entries/tag_index.html
{% extends 'entries/base_entries.html' %}

{% block title %}Tags{% endblock %}

{% block content_title %}Tags{% endblock %}

{% block content %}
    <ul>
        {% for tag in object_list.items %}
            <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
    {% include 'includes/page_links.html' %}
{% endblock %}